UPDATE XXKT_RR_IRP_EXTRACT SET WEEK_ID = 04;


CREATE SEQUENCE XXKT_PLNR_ADJUSTMENTS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE XXKT_CM_COMMITS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE XXKT_CM_EXCEPTIONS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE XXKT_UNPLANNED_REQUESTS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE XXKT_COLLAB_TASK_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE XXKT_COLLAB_CM_COMMITS(
	COMMIT_ID             	NUMBER,   
	PLANNER_ID            	VARCHAR2(25),
	SUPPLIER_ID           	VARCHAR2(25),
	PRODUCT               	VARCHAR2(100),
	NON_GSA_COMMIT_QTY		NUMBER,
	GSA_COMMIT_QTY			NUMBER,
	COMMIT_QUANTITY       	NUMBER,
	COMMIT_REASON         	VARCHAR2(50),
	COMMIT_COMMENTS       	VARCHAR2(500),
	CREATED_BY            	VARCHAR2(25),
	CREATION_DATE         	DATE,
	UPDATED_BY            	VARCHAR2(25),
	UPDATION_DATE         	DATE,
	WEEK_ID               	NUMBER,
	DEMAND_DATE           	DATE);


CREATE TABLE XXKT_COLLAB_PLNR_ADJUSTMENTS(
	ADJUSTMENT_ID          	NUMBER,
	PLANNER_ID             	VARCHAR2(25),
	SUPPLIER_ID				VARCHAR2(25),
	PRODUCT                 VARCHAR2(100),
	REQ_PLAN_NON_GSA_ADJ    NUMBER,
	REQ_PLAN_GSA_ADJ        NUMBER, 
	ADJUSTMENT_QUANTITY     NUMBER,
	ADJUSTMENT_TYPE         VARCHAR2(50),
	ADJUSTMENT_COMMENTS     VARCHAR2(500),
	CREATED_BY              VARCHAR2(50),
	CREATION_DATE           DATE,
	UPDATED_BY              VARCHAR2(50),
	UPDATION_DATE           DATE,
	WEEK_ID                 NUMBER,
	DEMAND_DATE           	DATE);


CREATE TABLE XXKT_COLLAB_USER_PREFERENCE(
    USER_ID                 NUMBER(10),
    USER_NAME           	VARCHAR2(25),
    PREFERENCE_NAME     	VARCHAR2(50),
    PREFERENCE_VALUE    	VARCHAR2(100)
);

CREATE TABLE XXKT_UNPLANNED_REQUESTS(
	REQUEST_ID				NUMBER(5),
	PLANNER_ID				VARCHAR2(10),
	SUPPLIER_ID				VARCHAR2(10),
	PRODUCT_FAMILY			VARCHAR2(100),
	PRODUCT_LINE			VARCHAR2(100),
	PRODUCT					VARCHAR2(100),
	REQUEST_QUANTITY		NUMBER(5),
	REQUEST_TYPE			VARCHAR2(50),
	REQUEST_COMMENTS		VARCHAR2(500),
	CREATED_BY				VARCHAR2(50),
	CREATION_DATE			DATE,
	UPDATED_BY				VARCHAR2(50),
	UPDATION_DATE			DATE,
	APPROVAL_STATUS			VARCHAR2(50),
	APPROVAL_WORKFLOW_ID	VARCHAR2(50),
	APPROVER_ID				VARCHAR2(50),
	APPROVED_DATE			DATE,
	WEEK_ID					NUMBER(5)
);

CREATE TABLE XXKT_COLLAB_TASK_DETAIL(
    TASK_REQUEST_ID     NUMBER(5),
    TASK_APPROVAL_ID    NUMBER(5),
    PLANNER				VARCHAR2(50),
    TASK_FROM           VARCHAR2(50),
    SUPPLIER			VARCHAR2(50),
    TASK_TO             VARCHAR2(50),
    PRODUCT             VARCHAR2(50),
    FORECAST_DATE       VARCHAR2(50),
    VARIANCES           VARCHAR2(50),
    TASK_STATUS         VARCHAR2(50),
    TASK_SUBJECT		VARCHAR2(200),
    TASK_MESSAGE		VARCHAR2(1000),
    CREATED_BY		    VARCHAR2(50),
	CREATION_DATE	    DATE,
	UPDATED_BY			VARCHAR2(50),
	UPDATION_DATE		DATE
);

CREATE TABLE XXKT_COLLAB_ADJ_RESN_DETAIL(
    AR_ID           VARCHAR2(100),
    AR_VALUE        VARCHAR2(100),
    AR_TYPE         VARCHAR2(10),
    CREATION_DATE   DATE DEFAULT SYSDATE
);

INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('T1', 'T1', 'A');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('T2', 'T2', 'A');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('T3', 'T3', 'A');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('T4', 'T4', 'A');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('T5', 'T5', 'A');


INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Turnkey LLM Shortages', 'Component/PCA Shortage', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Keysight Buy Sell/LTB Shortages', 'Short of Buy Sell/LTB Items', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('ECR/ECN', 'ECR/ECN', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Eceptions/Demand Upside', 'Demand Pull in /Big Deal', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Production Issues', 'Assembly Delay/Capacity Issue', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Testing Failure/Rework/Debug', 'Board Failure', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Quality Issue', 'Component/PCA/HLA/Box Quality', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Priority Changes', 'Keysight Requirement Change', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('Machine Calibration', 'Tester/Machine Send for Recall', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('MOQ/PPV Approval TAT', 'Approval More Than 24 Hours', 'R');
INSERT INTO XXKT_COLLAB_ADJ_RESN_DETAIL (AR_ID, AR_VALUE, AR_TYPE) VALUES('PO Management', 'Keysight Requirement Change', 'R');


CREATE TABLE XXKT_RR_IRP_EXTRACT(
	WEEK_ID                           NUMBER,       
	COMPONENT_PART                    VARCHAR2(50),
	COMPONENT_SITE                    VARCHAR2(50),
	DEMAND_DATE                       DATE,   
	REQ_PLAN_NON_GSA                  NUMBER,  
	REQ_PLAN_GSA                      NUMBER,  
	REQ_PLAN_SYS                      NUMBER,  
	REQ_PLAN_FORECAST                 NUMBER,  
	REQ_PLAN_BUFFER                   NUMBER,   
	REQ_PLAN_BUFFER_OPT_ADJ           NUMBER,   
	REQ_PLAN_KR_TOTAL_ORI             NUMBER,   
	REQ_PLAN_KR_TOTAL                 NUMBER,      
	MANUAL_PLAN_ADJUSTMENT            NUMBER,     
	ORIGINAL_IRP_TOTAL_ORIGINAL       NUMBER,    
	FINAL_IRP_TOTAL_FINAL             NUMBER,     
	OPEN_PO_NON_GSA                   NUMBER,    
	OPEN_PO_GSA                       NUMBER,   
	PRODUCT_FAMILY                    VARCHAR2(50),
	BUILD_TYPE                        VARCHAR2(50),
	SUPPLIER                          VARCHAR2(250),
	COUNT                             NUMBER,
	DATA_OWNER                        VARCHAR2(50),
	PART_NUMBER                       VARCHAR2(50),
	PART_SITE                         VARCHAR2(50),
	BUCKET_DATE                       DATE,  
	HEADER_VERSION                    DATE,    
	PLANNER_ADJUSTMENT_QTY            NUMBER,   
	REMARKS                           VARCHAR2(250)
);


CREATE TABLE XXKT_COLLAB_ITEM_MASTER(
	ITEM_ID                NUMBER,
	APPLICATION            VARCHAR2(200),
	PART_NAME              VARCHAR2(200),
	PART_SITE              VARCHAR2(200),
	PRODUCT_FAMILY         VARCHAR2(200),
	CID_MAP                VARCHAR2(200),
	BUILD_TYPE             VARCHAR2(200),
	CTO_FLAG               VARCHAR2(200),
	IN_TESTING_FLAG        VARCHAR2(200),
	COUNTABLE_FLAG         VARCHAR2(200),
	CONTRACT_PERIOD        NUMBER,
	CONTRACT_RATIO         NUMBER,
	KANBAN_LT              NUMBER,
	PROCESS_LT             NUMBER,
	SHIP_REL_DAYS          NUMBER,
	POST_PROC_LT           NUMBER,
	LAST_UPDATE_DATE       DATE,
	SUPPLIER_NAME          VARCHAR2(200),
	CMA_REMARKS            VARCHAR2(200),
	BU                     VARCHAR2(200),
	DEPT                   VARCHAR2(200),
	BASE_KEY               VARCHAR2(200)
);

